server:
  port: 9090


spring:
  application:
    name: my-market-app-reactive
  r2dbc:
    url: r2dbc:h2:mem:///marketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  sql:
    init:
      mode: always
      platform: h2

logging:
  level:
    org.springframework.web: DEBUG
    ru.ugaforever.my_market_app: DEBUG
