server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: backend

  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: ${SPRING_DATA_REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

  r2dbc:
    url: r2dbc:h2:mem:///marketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode: always
      platform: h2

  security:
    oauth2:
      client:
        registration:
          # Регистрация для payment service (Client Credentials Flow)
          payment-service:
            provider: keycloak
            client-id: payment-service
            client-secret: 6MwDZRNt9EAGr3ttNT2XK6pUWMHNTIHC
            authorization-grant-type: client_credentials
            scope: openid

          # Регистрация для пользователей (Authorization Code Flow)
          keycloak:
            provider: keycloak
            client-id: backend
            client-secret: W4sE652I3MuVSmWeu7hJp4dgjhPTFNLY
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9092/realms/my-market-app
payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:9091/api/v1}
    connect-timeout: 5000
    read-timeout: 5000

logging:
  level:
    org.springframework.web: DEBUG
    ru.ugaforever.my_market_app: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
